### ISSUE TITLE
Deduplication issue - Not passing the same event_id via TAG and API within a timeframe

### ISSUE THREAD

**Issue by mayornova** [mbaersch/event-id#2]
Hello,

we are using the mbaersch Event ID variable in the browser-side GTM - 1). In the Pinterest pixel tag and 2). In the GA4 tag, that is sending info to server-side GTM (where we have the Pinterest API set up). 

In the Pinterest interface, we can see that the Page view and Add to Cart events have a high deduplication rate (80-90%), but the Checkout (Purchase) event doesn't - it reached around 20-30%. 

According to the Pinterest team - there is an issue with "not passing the same event_id via TAG and API within a timeframe". They have suggested posting an issue here.

Any idea what could be causing this?

**Comment by mbaersch** [comment]
you are probably sending events from the browser and via server at different events in the dataLayer and thus IDs do not match. Try to use the same trigger event for both tags or use a cached event id if that is not possible. You find this link in the readme file as well: https://gist.github.com/mbaersch/5919bc1c795031183a525cb8c64a9352

**Comment by mayornova** [comment]
The trigger is one and the same, checked several times. 

We will try the option to use cached event id. Thank you!
